CREATE TABLE IF NOT EXISTS "dialog" (
                          "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                          "userId" INTEGER NOT NULL,
                          "username" VARCHAR(64) NOT NULL,
                          "contextId" INTEGER NOT NULL,
                          "question" TEXT NOT NULL,
                          "answer" TEXT NOT NULL,
                          "isNewContext" BOOLEAN NOT NULL,
                          PRIMARY KEY("id")
);